config/routes.rb
Rails.application.routes.draw do
  resources :price_reports, only: [:show, :index]
  resources :stations, only: [:show, :index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "stations#index"
end

app/models/station.rb
require 'pipeline_stage'
require 'pipeline_operator'

class Station
  include Mongoid::Document

  field :_id, type: String
  field :name, type: String
  field :brand, type: String
  field :street, type: String
  field :house_number, type: Integer
  field :post_code, type: Integer
  field :place, type: String
  field :latitude, type: Float
  field :longitude, type: Float

  has_many :price_reports, inverse_of: :station, order: :report_time.desc do
    def latest_price
      first
    end
  end

  def changes_per_day
    result = PriceReport.collection.aggregate(
      [
        match_station,
        *create_daily_stats
      ]
    ).to_a[0]

    result == nil ? 0 : result['changesPerDay']
  end

  def price_differences
    PriceReport.collection.aggregate(
      [
        *get_diff_pipeline,
        sort_by_timeframe
      ]
    )
  end

  def aggregated_prices_pipeline
    [
      match_station,
      create_timeframe_stats,
      add_average_change,
      shape_output_document,
    ]
  end

  def aggregated_prices
    PriceReport.collection.aggregate(
      [
        *aggregated_prices_pipeline,
        sort_by_timeframe,
      ]
    ).to_a
  end

  def popular_increase_times
    PriceReport.collection.aggregate(
      get_change_count_pipeline(match_price_increases)
    )
  end

  def popular_decrease_times
    PriceReport.collection.aggregate(
      get_change_count_pipeline(match_price_decreases)
    )
  end

  def popular_cheapest_times
    PriceReport.collection.aggregate(get_popular_extreme_times_pipeline('lowest'))
  end

  def popular_expensive_times
    PriceReport.collection.aggregate(get_popular_extreme_times_pipeline('highest'))
  end

  private
    def match_station
      PipelineStage.match(
        station_id: self._id,
        previous_price_report: { '$ne' => nil })
    end

    def create_timeframe_stats
      PipelineStage.group(
        '$report_timeframe',
        changes: PipelineOperator.sum(1),
        dieselChange: PipelineOperator.avg('$diesel.change'),
        e5Change: PipelineOperator.avg('$e5.change'),
        e10Change: PipelineOperator.avg('$e10.change'),
      )
    end

    def create_daily_stats
      [
        PipelineStage.group(
          {
            'year' => PipelineOperator.year('$report_time'),
            'month' => PipelineOperator.month('$report_time'),
            'day' => PipelineOperator.day_of_month('$report_time'),
          },
          changes: PipelineOperator.sum(1)
        ),
        PipelineStage.group(
          nil,
          changesPerDay: PipelineOperator.avg('$changes'),
        )
      ]
    end

    def add_average_change
      PipelineStage.add_fields(
        averageChange: PipelineOperator.avg('$dieselChange', '$e5Change', '$e10Change')
      )
    end

    def match_price_increases
      PipelineStage.match(averageChange: { '$gt' => 0 })
    end

    def match_price_decreases
      PipelineStage.match(averageChange: { '$lt' => 0 })
    end

    def sort_by_timeframe
      PipelineStage.sort(
        'timeframe.hour': 1,
        'timeframe.minute': 1,
      )
    end

    def sort_by_changes
      PipelineStage.sort(
        changes: -1,
        'timeframe.hour': 1,
        'timeframe.minute': 1,
      )
    end

    def shape_output_document
      PipelineStage.add_fields(
        timeframe: '$_id'
      )
    end

    def get_change_count_pipeline(matcher)
      [
        *aggregated_prices_pipeline,
        matcher,
        sort_by_changes,
        PipelineStage.limit(5)
      ]
    end

    def group_data_by_day
      PipelineStage.group(
        {
          'year' => PipelineOperator.year('$report_time'),
          'month' => PipelineOperator.month('$report_time'),
          'day' => PipelineOperator.day_of_month('$report_time'),
        },
        changes: PipelineOperator.sum(1),
        dieselData: PipelineOperator.push(
          {
            'report_timeframe' => '$report_timeframe',
            'price' => '$diesel.price',
            'change' => '$diesel.change'
          }
        ),
        e5Data: PipelineOperator.push(
          {
            'report_timeframe' => '$report_timeframe',
            'price' => '$e5.price',
            'change' => '$e5.change'
          }
        ),
        e10Data: PipelineOperator.push(
          {
            'report_timeframe' => '$report_timeframe',
            'price' => '$e10.price',
            'change' => '$e10.change'
          }
        )
      )
    end

    def get_fuel_difference_pipeline(fuel_type)
      [
        {
          # TODO: Figure out how to pass a variably named param to a double-splat method argument
          '$addFields' => {
            data_field_name(fuel_type) => PipelineOperator.sort_array(
              '$' + data_field_name(fuel_type),
              'price' => 1,
              'report_timeframe.hour' => 1,
              'report_timeframe.minute' => 1,
            )
          }
        },
        {
          '$addFields' => {
            fuel_type => {
              'lowest' => PipelineOperator.first('$' + data_field_name(fuel_type)),
              'highest' => PipelineOperator.last('$' + data_field_name(fuel_type)),
            }
          }
        },
        {
          '$addFields' => {
            data_field_name(fuel_type) => PipelineOperator.sort_array(
              PipelineOperator.map(
                '$' + data_field_name(fuel_type),
                'price_report',
                {
                  'report_timeframe' => '$$price_report.report_timeframe',
                  'higher_than_lowest' => PipelineOperator.subtract(
                    '$$price_report.price',
                    '$$ROOT.' + fuel_type + '.lowest.price',
                  )
                }
              ),
              'report_timeframe.hour' => 1,
              'report_timeframe.minute' => 1,
            )
          }
        },
        PipelineStage.unwind('$' + data_field_name(fuel_type)),
        PipelineStage.group(
          '$' + data_field_name(fuel_type) + '.report_timeframe',
          higherThanLowest: PipelineOperator.avg('$' + data_field_name(fuel_type) + '.higher_than_lowest'),
          times: PipelineOperator.sum(1),
        ),
        PipelineStage.replace_with(
          {
            '_id' => '$_id',
            fuel_type => {
              'higherThanLowest' => '$higherThanLowest',
              'times' => '$times',
              'impact' => PipelineOperator.multiply('$higherThanLowest', '$times'),
            }
          }
        ),
      ]
    end

    def get_diff_pipeline
      [
        match_station,
        group_data_by_day,
        PipelineStage.facet(
          diesel: get_fuel_difference_pipeline('diesel'),
          e5: get_fuel_difference_pipeline('e5'),
          e10: get_fuel_difference_pipeline('e10'),
        ),
        PipelineStage.replace_with(
          {
            'data' => PipelineOperator.concat_arrays('$diesel', '$e5', '$e10')
          }
        ),
        PipelineStage.unwind('$data'),
        PipelineStage.group(
          '$data._id',
          diesel: PipelineOperator.push('$data.diesel'),
          e5: PipelineOperator.push('$data.e5'),
          e10: PipelineOperator.push('$data.e10'),
        ),
        PipelineStage.add_fields(
          diesel: PipelineOperator.first('$diesel'),
          e5: PipelineOperator.first('$e5'),
          e10: PipelineOperator.first('$e10'),
        ),
        PipelineStage.add_fields(
          average: {
            'higherThanLowest' => PipelineOperator.avg(
              '$diesel.higherThanLowest',
              '$e5.higherThanLowest',
              '$e10.higherThanLowest'
            ),
            'times' => PipelineOperator.avg(
              '$diesel.times',
              '$e5.times',
              '$e10.times'
            )
          }
        ),
        PipelineStage.add_fields(
          average: {
            'impact' => PipelineOperator.multiply('$average.higherThanLowest', '$average.times'),
          },
        ),
        shape_output_document
      ]
    end

    def sort_fuel_data_by_price(fuel_type)
      PipelineOperator.sort_array(
        '$' + data_field_name(fuel_type),
        'price' => 1,
        'report_timeframe.hour' => 1,
        'report_timeframe.minute' => 1
      )
    end

    def find_extreme_price_for_fuel(fuel_type)
      {
        'lowestEntry' => PipelineOperator.first('$' + data_field_name(fuel_type)),
        'highestEntry' => PipelineOperator.last('$' + data_field_name(fuel_type)),
      }
    end

    def find_extreme_times_for_fuel(fuel_type)
      {
        'lowestTimes' => PipelineOperator.filter(
          '$' + data_field_name(fuel_type),
          PipelineOperator.eq(
            '$$priceReport.price',
            '$' + fuel_type + '.lowestEntry.price'
          ),
          'priceReport',
        ),
        'highestTimes' => PipelineOperator.filter(
          '$' + data_field_name(fuel_type),
          PipelineOperator.eq(
            '$$priceReport.price',
            '$' + fuel_type + '.highestEntry.price'
          ),
          'priceReport',
        ),
      }
    end

    def group_extreme_times_for_fuel(fuel_type, type, limit)
      [
        PipelineStage.unwind('$' + fuel_type + '.' + type + 'Times'),
        PipelineStage.group(
          '$' + fuel_type + '.' + type + 'Times.report_timeframe',
          count: PipelineOperator.sum(1),
        ),
        PipelineStage.sort(count: -1),
        PipelineStage.limit(limit),
      ]
    end

    def shape_extreme_times_for_fuel(fuel_type)
      PipelineOperator.map(
        '$' + fuel_type,
        'report',
        {
          fuel_type => {
            'timeframe' => '$$report._id',
            'count' => '$$report.count'
          }
        }
      )
    end

    def shape_extreme_times(limit)
      elements = []

      for i in 0..limit-1 do
        elements.push(
          PipelineOperator.merge_objects(
            PipelineOperator.array_elem_at('$diesel', i),

app/controllers/stations_controller.rb
class StationsController < ApplicationController
  before_action :set_station, only: %i[ show ]

  # GET /stations or /stations.json
  def index
    @post_code = params[:post_code] ? params[:post_code] : 82140
    @stations = Station.where(post_code: @post_code)
    # @stations = Station.all
    # @stations = Station.order(:uuid.asc).page params[:page]
  end

  # GET /stations/1 or /stations/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_station
      @station = Station.find(params[:id])
    end
end

app/helpers/stations_helper.rb
module StationsHelper
end

app/views/stations/_price.html.erb
<%= sprintf('%.3f €', price.fdiv(1000)) %>

app/views/stations/_price_change.html.erb
<% if change > 0 %>
  <i class="bi-arrow-up-right text-danger"></i>
<% else %>
  <% if change < 0  %>
    <i class="bi-arrow-down-right text-success"></i>
  <% else %>
    <i class="bi-arrow-right"></i>
  <% end %>
<% end %>

<%= sprintf('%+.3f €', change.fdiv(1000)) %>

app/views/stations/_timeframe.html.erb
<%= sprintf('%02d:%02d', timeframe['hour'], timeframe['minute']) %>

app/views/stations/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Stations in <%= @post_code %></h1>

<div id="stations" class="row row-cols-3 gy-4">
  <% if @stations.blank? %>
    <div class="alert alert-warning" role="alert">No stations found for this post code!</div>
  <% end %>
  <% @stations.each do |station| %>
    <div class="col">
        <div id="<%= dom_id station %>" class="card">
          <div class="card-body">
            <h5 class="text-truncate"><%= station.name %></h5>
            <h6 class="card-subtitle text-muted"><%= station.brand %></h6>
            <p class="card-text">
              <address>
                <%= station.street %> <%= station.house_number %><br />
                <%= station.post_code %> <%= station.place %>
              </address>
            </p>
            <p class="card-text">
              <%= station.changes_per_day %> changes per day
            </p>
          </div>

          <ul class="list-group list-group-flush">
            <% if station.price_reports.latest_price -%>
              <li class="list-group-item">Diesel: <%= render "price", price: station.price_reports.latest_price.diesel.price %></li>
              <li class="list-group-item">E5: <%= render "price", price: station.price_reports.latest_price.e5.price %></li>
              <li class="list-group-item">E10: <%= render "price", price: station.price_reports.latest_price.e10.price %></li>
            <% else %>
              <li class="list-group-item">Diesel: --</li>
              <li class="list-group-item">E5: --</li>
              <li class="list-group-item">E10: --</li>
            <% end -%>
          </ul>

          <div class="card-body">
            <%= link_to "Show this station", station, class: "card-link" %>
          </div>
        </div>
    </div>
  <% end %>
</div>

<%#= paginate @stations %>

app/views/stations/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><%= link_to "Stations", stations_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @station.name %></li>
  </ol>
</nav>

<div class="row row-cols-2 mb-4">
  <div class="col">
    <div id="<%= dom_id @station %>" class="card">
      <p class="card-img-top text-center">TODO: Map</p>
      <div class="card-body">
        <h5 class="text-truncate"><%= @station.name %></h5>
        <h6 class="card-subtitle text-muted"><%= @station.brand %></h6>
        <p class="card-text">
          <address>
            <%= @station.street %> <%= @station.house_number %><br />
            <%= @station.post_code %> <%= @station.place %>
          </address>
        </p>
        <p class="card-text">
          <%= @station.changes_per_day %> changes per day
        </p>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5>Latest prices</h5>
        <% if @station.price_reports.latest_price -%>
          <h6 class="card-subtitle text-muted">Reported on <%= @station.price_reports.latest_price.report_time %></h6>
          <dl>
            <dt>Diesel</dt>
            <dd><%= render "price", price: @station.price_reports.latest_price.diesel.price %></dd>
            <dt>E5</dt>
            <dd><%= render "price", price: @station.price_reports.latest_price.e5.price %></dd>
            <dt>E10</dt>
            <dd><%= render "price", price: @station.price_reports.latest_price.e10.price %></dd>
          </dl>
        <% else %>
          <h6 class="card-subtitle text-muted">No prices reported</h6>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class="row row-cols-2 mb-4">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5>Most popular expensive times</h5>
        <table class="table table-striped table-hover table-bordered">
          <thead>
          <tr>
            <th>Diesel</th>
            <th>E5</th>
            <th>E10</th>
          </tr>
          </thead>
          <tbody>
            <% @station.popular_expensive_times.each do |entry| %>
              <tr>
                <td><%= render "timeframe", timeframe: entry['diesel']['timeframe'] %> (<%= entry['diesel']['count'].to_i %> times)</td>
                <td><%= render "timeframe", timeframe: entry['e5']['timeframe'] %> (<%= entry['e5']['count'].to_i %> times)</td>
                <td><%= render "timeframe", timeframe: entry['e10']['timeframe'] %> (<%= entry['e10']['count'].to_i %> times)</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5>Most popular cheap times</h5>
        <table class="table table-striped table-hover table-bordered">
          <thead>
          <tr>
            <th>Diesel</th>
            <th>E5</th>
            <th>E10</th>
          </tr>
          </thead>
          <tbody>
            <% @station.popular_cheapest_times.each do |entry| %>
              <tr>
                <td><%= render "timeframe", timeframe: entry['diesel']['timeframe'] %> (<%= entry['diesel']['count'].to_i %> times)</td>
                <td><%= render "timeframe", timeframe: entry['e5']['timeframe'] %> (<%= entry['e5']['count'].to_i %> times)</td>
                <td><%= render "timeframe", timeframe: entry['e10']['timeframe'] %> (<%= entry['e10']['count'].to_i %> times)</td>
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

<div class="row row-cols-2 mb-4">
  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5>Most popular increase times</h5>
        <dl>
          <% @station.popular_increase_times.each do |aggregated_price| %>
            <dt><%= render "timeframe", timeframe: aggregated_price['timeframe'] %> (<%= aggregated_price['changes'] %> changes)</dt>
            <dd><%= render "price_change", change: aggregated_price['averageChange'] %></dd>
          <% end %>
        </dl>
      </div>
    </div>
  </div>

  <div class="col">
    <div class="card">
      <div class="card-body">
        <h5>Most popular decrease times</h5>
        <dl>
          <% @station.popular_decrease_times.each do |aggregated_price| %>
            <dt><%= render "timeframe", timeframe: aggregated_price['timeframe'] %> (<%= aggregated_price['changes'] %> changes)</dt>
            <dd><%= render "price_change", change: aggregated_price['averageChange'] %></dd>
          <% end %>
        </dl>
      </div>
    </div>
  </div>
</div>

<h5>Average price difference</h5>

<table id="priceDifferences" class="table table-striped table-hover table-bordered mb-4">
  <thead>
  <tr>
    <th>Time</th>
    <th>Diesel (times)</th>
    <th>E5 (times)</th>
    <th>E10 (times)</th>
  </tr>
  </thead>
  <tbody>
  <% @station.price_differences.each do |price_difference| %>
    <tr>
      <td><%= render "timeframe", timeframe: price_difference['timeframe'] %></td>
      <td><%= render "price_change", change: price_difference['diesel']['higherThanLowest'] %> (<%= price_difference['diesel']['times'].to_i %> times)</td>
      <td><%= render "price_change", change: price_difference['e5']['higherThanLowest'] %> (<%= price_difference['e5']['times'].to_i %> times)</td>
      <td><%= render "price_change", change: price_difference['e10']['higherThanLowest'] %> (<%= price_difference['e10']['times'].to_i %> times)</td>
    </tr>
  <% end %>
  </tbody>
  <caption>This table shows the average price difference at each time frame compared to the lowest price each day.</caption>
</table>

<h5>Price changes</h5>

<table class="table table-striped table-hover table-bordered mb-4">
  <thead>
  <tr>
    <th>Time</th>
    <th>Changes</th>
    <th>Diesel</th>
    <th>E5</th>
    <th>E10</th>
  </tr>
  </thead>
  <tbody>
  <% @station.aggregated_prices.each do |aggregated_price| %>
    <tr>
      <td><%= render "timeframe", timeframe: aggregated_price['timeframe'] %></td>
      <td><%= aggregated_price['changes'] %></td>
      <td><%= render "price_change", change: aggregated_price['dieselChange'] %></td>
      <td><%= render "price_change", change: aggregated_price['e5Change'] %></td>
      <td><%= render "price_change", change: aggregated_price['e10Change'] %></td>
    </tr>
  <% end %>
  </tbody>
  <caption>This table shows the average price change for each time frame compared to the previous time.</caption>
</table>