config/routes.rb
Rails.application.routes.draw do
  resources :price_reports, only: [:show, :index]
  resources :stations, only: [:show, :index]
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "stations#index"
end

app/models/price_report.rb
class PriceReport
  include Mongoid::Document

  belongs_to :station, inverse_of: :price_reports

  field :report_time, type: Time

  embeds_one :diesel, class_name: "Price"
  embeds_one :e5, class_name: "Price"
  embeds_one :e10, class_name: "Price"
end

app/controllers/price_reports_controller.rb
class PriceReportsController < ApplicationController
  before_action :set_price_report, only: %i[ show ]

  # GET /price_reports or /price_reports.json
  def index
    @price_reports = PriceReport.order(:_id.asc).page params[:page]
  end

  # GET /price_reports/1 or /price_reports/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_price_report
      @price_report = PriceReport.find(params[:id])
    end
end

app/helpers/price_reports_helper.rb
module PriceReportsHelper
end

app/views/price_reports/_price_report.html.erb
<div id="<%= dom_id price_report %>">
  <p>
    <strong>Report time:</strong>
    <%= price_report.report_time %>
  </p>

  <table>
    <tr>
      <th>Fuel type</th>
      <th>Price</th>
      <th>Changed</th>
    </tr>
    <tr>
      <td>Diesel</td>
      <td><%= price_report.diesel.price %></td>
      <td><%= price_report.diesel.price_changed %></td>
    </tr>
    <tr>
      <td>Petrol E5</td>
      <td><%= price_report.e5.price %></td>
      <td><%= price_report.e5.price_changed %></td>
    </tr>
    <tr>
      <td>Petrol E10</td>
      <td><%= price_report.e10.price %></td>
      <td><%= price_report.e10.price_changed %></td>
    </tr>
  </table>

</div>

app/views/price_reports/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Price reports</h1>

<div id="price_reports">
  <% @price_reports.each do |price_report| %>
    <%= render price_report %>
    <p>
      <%= link_to "Show this price report", price_report %>
    </p>
  <% end %>
</div>

<%#= paginate @price_reports %>

app/views/price_reports/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @price_report %>

<div>
  <%= link_to "Back to price reports", price_reports_path %>
</div>